export declare const motd: import("node-karin").Command<keyof import("node-karin").MessageEventMap>;
export declare const addServer: import("node-karin").Command<keyof import("node-karin").MessageEventMap>;
export declare const removeServer: import("node-karin").Command<keyof import("node-karin").MessageEventMap>;
export declare const listServer: import("node-karin").Command<keyof import("node-karin").MessageEventMap>;
export declare const serverInfo: import("node-karin").Command<keyof import("node-karin").MessageEventMap>;
export declare const wlon: import("node-karin").Command<keyof import("node-karin").MessageEventMap>;
export declare const wloff: import("node-karin").Command<keyof import("node-karin").MessageEventMap>;
export declare const wllist: import("node-karin").Command<keyof import("node-karin").MessageEventMap>;
export declare const rcon: import("node-karin").Command<keyof import("node-karin").MessageEventMap>;
export declare const bind: import("node-karin").Command<keyof import("node-karin").MessageEventMap>;
export declare const unbind: import("node-karin").Command<keyof import("node-karin").MessageEventMap>;
export declare const unbindAdmin: import("node-karin").Command<keyof import("node-karin").MessageEventMap>;
export declare const ban: import("node-karin").Command<keyof import("node-karin").MessageEventMap>;
export declare const unban: import("node-karin").Command<keyof import("node-karin").MessageEventMap>;
export declare const apply: import("node-karin").Command<keyof import("node-karin").MessageEventMap>;
export declare const revoke: import("node-karin").Command<keyof import("node-karin").MessageEventMap>;
export declare const groupMemberBanNotice: import("node-karin").Accept<"notice.groupMemberBan">;
export declare const groupMemberAddNotice: import("node-karin").Accept<"notice.groupMemberAdd">;
export declare const help: import("node-karin").Command<keyof import("node-karin").MessageEventMap>;
